fourth task: creating simple server
Kilovatov/node-ex pull request #3
Opened 2017-10-27 17:28 UTC by SKolevatov

2017-11-01 14:49 UTC, ubcent requested changes

2017-11-01 14:49 UTC, ubcent commented on app.js
> +const {parseQuery} = require('./middlewares/queryParsingMiddleware');
Рекомендую в папке middlewares создать index.js, в котором экспортить все, что в этой папке есть, тогда импорты будут выглядеть очень эстетично:
```javascript
const {parseQuery, parseCookie} = require('./middlewares');
```

2017-11-01 14:49 UTC, ubcent commented on app.js
> +const router = express.Router();
Роуты лучше тоже вынести в отдельные модули, группируя по смыслу. Например, в файле /routes/products.js положить все роуты, начинающиеся с products, а в /routes/users.js - начинающееся с users

2017-11-01 14:49 UTC, ubcent commented on app.js
> +router.param('id', function(req, res, next, id) {
Лучше переназвать, т.к. потом может появиться семество роутов `users/:id`

2017-11-01 14:49 UTC, ubcent commented on http-servers/json-server.js
> +const product = {
Лучше перенести это на самый верх, т.к. const и let видны только после создания. Здесь работает, т.к. функция асинхронна.

2017-11-02 14:27 UTC, ubcent approved these changes

2017-11-02 14:29 UTC, Kilovatov approved these changes

2017-11-02 14:29 UTC, merged